#! /bin/bash

if [[ ! -d ~/.nvm ]]; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
  source ~/.bashrc
  nvm install v4.1.2
fi
if [ ! $(which coffee) ]; then
  npm install -g coffee-script
fi
cat src/*.coffee | coffee --compile --stdio > compiled/hebrewDate.js
cat qunit/*.coffee | coffee --compile --stdio > qunit/tests.js
haml qunit/qunit.haml qunit/qunit.html
