#! /bin/bash -xe

if [[ ! -d ~/.nvm ]]; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  source ~/.nvm/nvm.sh
  nvm install node
  nvm use node
fi
if [ ! $(which coffee) ]; then
  npm install -g coffee-script
fi
if [ ! $(which haml-js) ]; then
  npm install -g haml
fi
cat src/*.coffee | coffee --compile --stdio > compiled/hebrewDate.js
cat qunit/*.coffee | coffee --compile --stdio > qunit/tests.js
haml-js qunit/qunit.haml qunit/qunit.html
